from app.models.ai_prediction import AIPrediction
from app.models.assignment import Assignment
from app.models.attendance import Attendance
from app.models.class_model import Class
from app.models.course import Course
from app.models.enrollment import Enrollment
from app.models.exam import Exam
from app.models.exam_result import ExamResult
from app.models.performance_record import PerformanceRecord
from app.models.recommendation import Recommendation
from app.models.student import Student
from app.models.submission import Submission
from app.models.teacher import Teacher
from app.models.user import User
